if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/compiler/canonicalization_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/compiler/canonicalization_test[1]_tests.cmake")
else()
  add_test(canonicalization_test_NOT_BUILT canonicalization_test_NOT_BUILT)
endif()
