if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/ec/elliptic_curve_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/ec/elliptic_curve_test[1]_tests.cmake")
else()
  add_test(elliptic_curve_test_NOT_BUILT elliptic_curve_test_NOT_BUILT)
endif()
