if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/sumcheck/quad_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/sumcheck/quad_test[1]_tests.cmake")
else()
  add_test(quad_test_NOT_BUILT quad_test_NOT_BUILT)
endif()
