if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/sha/flatsha256_circuit_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/sha/flatsha256_circuit_test[1]_tests.cmake")
else()
  add_test(flatsha256_circuit_test_NOT_BUILT flatsha256_circuit_test_NOT_BUILT)
endif()
