if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/crt_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/crt_test[1]_tests.cmake")
else()
  add_test(crt_test_NOT_BUILT crt_test_NOT_BUILT)
endif()
