if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/fft_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/fft_test[1]_tests.cmake")
else()
  add_test(fft_test_NOT_BUILT fft_test_NOT_BUILT)
endif()
