if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/fp2_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/fp2_test[1]_tests.cmake")
else()
  add_test(fp2_test_NOT_BUILT fp2_test_NOT_BUILT)
endif()
