if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/nat_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/nat_test[1]_tests.cmake")
else()
  add_test(nat_test_NOT_BUILT nat_test_NOT_BUILT)
endif()
