if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/nussbaumerfp2_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/nussbaumerfp2_test[1]_tests.cmake")
else()
  add_test(nussbaumerfp2_test_NOT_BUILT nussbaumerfp2_test_NOT_BUILT)
endif()
