if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/sysdep_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/algebra/sysdep_test[1]_tests.cmake")
else()
  add_test(sysdep_test_NOT_BUILT sysdep_test_NOT_BUILT)
endif()
