if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/arrays/eqs_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/arrays/eqs_test[1]_tests.cmake")
else()
  add_test(eqs_test_NOT_BUILT eqs_test_NOT_BUILT)
endif()
