if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/logic/logic_circuit_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/logic/logic_circuit_test[1]_tests.cmake")
else()
  add_test(logic_circuit_test_NOT_BUILT logic_circuit_test_NOT_BUILT)
endif()
