if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/logic/routing_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/logic/routing_test[1]_tests.cmake")
else()
  add_test(routing_test_NOT_BUILT routing_test_NOT_BUILT)
endif()
