if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/sha3/sha3_reference_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/sha3/sha3_reference_test[1]_tests.cmake")
else()
  add_test(sha3_reference_test_NOT_BUILT sha3_reference_test_NOT_BUILT)
endif()
