if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/cbor_parser/mso_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/cbor_parser/mso_test[1]_tests.cmake")
else()
  add_test(mso_test_NOT_BUILT mso_test_NOT_BUILT)
endif()
