if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/cbor_parser/scan_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/cbor_parser/scan_test[1]_tests.cmake")
else()
  add_test(scan_test_NOT_BUILT scan_test_NOT_BUILT)
endif()
