if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/mdoc/mdoc_zk_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/mdoc/mdoc_zk_test[1]_tests.cmake")
else()
  add_test(mdoc_zk_test_NOT_BUILT mdoc_zk_test_NOT_BUILT)
endif()
