if(EXISTS "/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/ecdsa/verify_external_test[1]_tests.cmake")
  include("/mnt/c/Users/rauld/Documents/4o+TFG/longfellow-zk/lib/circuits/ecdsa/verify_external_test[1]_tests.cmake")
else()
  add_test(verify_external_test_NOT_BUILT verify_external_test_NOT_BUILT)
endif()
